package com.example.peertopeer.research

data class ResearchEvent(
    val elapsedMs: Long,
    val event: String,
    val messageId: String,
    val protocol: String,
    val currentNode: String,
    val nextHop: String? = null,
    val destination: String? = null,
    /** Stage proposed directly from the unmodified Q threshold. */
    val rawStage: String? = null,
    /** Stage actually used after the two-observation hysteresis gate. */
    val decisionStage: String? = null,
    val hysteresisStatus: String? = null,
    val stage: String? = null,
    /** Q directly recalculated from D/F/R/T/S/B. */
    val qRaw: Double? = null,
    /** Q used for the decision; currently equal to qRaw because hysteresis holds stages, not values. */
    val qDecision: Double? = null,
    val confidence: Double? = null,
    val success: Boolean? = null,
    val latencyMs: Long? = null,
    val route: String? = null,
    val backupHop: String? = null,
    val backupRoute: String? = null,
    val routeConfidence: Double? = null,
    val routeCost: Double? = null,
    val d: Double? = null,
    val f: Double? = null,
    val r: Double? = null,
    val t: Double? = null,
    val s: Double? = null,
    val b: Double? = null,
    val rssiDbm: Int? = null,
    val rawRssiDbm: Int? = null,
    val rssiSampleCount: Int? = null,
    val deliveryAttempts: Int? = null,
    val hopAckSuccesses: Int? = null,
    val medianHopAckRttMs: Double? = null,
    val medianGattWriteMs: Double? = null,
    val freshnessAgeMs: Long? = null,
    val instabilityEvents: Int? = null,
    val gattFailureCount: Int? = null,
    val ackTimeoutCount: Int? = null,
    val disconnectCount: Int? = null,
    val measurementStatus: String? = null,
    /** B is fixed at 1.0 to match the zero-energy-penalty simulation. */
    val bSource: String? = null,
    /** Separates direct chat, group chat, control and formal experiment evidence. */
    val trafficType: String? = null,
    val queueDepth: Int? = null,
    val queueCapacity: Int? = null,
    val queueScaleK: Double? = null,
    val queuePressure: Double? = null,
    val mmReason: String? = null,
    val carbleReason: String? = null,
    val forwardingAction: String? = null,
    val candidateRoutes: String? = null,
    val runLabel: String? = null,
    val conditionLabel: String? = null,
    val epochMs: Long = System.currentTimeMillis(),
    val sessionId: String? = null,
    val sourceNode: String? = null,
    val previousHop: String? = null,
    val packetType: String? = null,
    val sequence: Int? = null,
    val hopCount: Int? = null,
    val totalPackets: Int? = null,
    val ackedPackets: Int? = null,
    /** Canonical source-side packet result fields. Populated only for formal EXPERIMENT packets. */
    val finalResult: String? = null,
    val attemptCount: Int? = null,
    val retransmissionCount: Int? = null,
    val backupActivationCount: Int? = null,
    val queueResidenceMs: Long? = null,
    val deliveredBeforeTtl: Boolean? = null,
    val note: String? = null,
    val deviceModel: String? = null,
    val androidApi: Int? = null,
    val appVersion: String? = null
)
